export const getGithubCallback = async () => {
  try {
    console.log('callback!!!!!!');
  } catch (err) {
    console.log('err', err);
  }
};
